DROP TABLE IF EXISTS users CASCADE;
DROP SEQUENCE IF EXISTS users_id_seq CASCADE;

DROP TABLE IF EXISTS user_roles CASCADE;
DROP SEQUENCE IF EXISTS user_roles_id_seq CASCADE;

DROP TABLE IF EXISTS films CASCADE;
DROP SEQUENCE IF EXISTS films_id_seq CASCADE;

DROP TABLE IF EXISTS discounts CASCADE;
DROP SEQUENCE IF EXISTS discounts_id_seq CASCADE;

DROP TABLE IF EXISTS baskets CASCADE;
DROP SEQUENCE IF EXISTS baskets_id_seq CASCADE;

DROP TABLE IF EXISTS orders CASCADE;
DROP SEQUENCE IF EXISTS orders_id_seq CASCADE;

DROP TABLE IF EXISTS user_discounts CASCADE;
DROP SEQUENCE IF EXISTS user_discounts_id_seq CASCADE;

DROP TABLE IF EXISTS payments CASCADE;
DROP SEQUENCE IF EXISTS payments_id_seq CASCADE;